#define MK_3_SPEED

#define MK_C_OFFSET_0 4
#define MK_C_INTERVAL_0 16

#define MK_C_OFFSET_1 16
#define MK_C_INTERVAL_1 16

#define MK_C_OFFSET_2 32
#define MK_C_INTERVAL_2 16

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_KEYRELEASES
